InternalClassType: Method
Coordinate3D: [26,-7,0]
Name: changeUserSettings
Origin: e323fd22-5471-40c5-a13c-6e974c6e8831
Program: |+1
 -- called by: EndOfAllExperiments, Start (button)
 -- val = "read" read and store the current settings and switch off the animation
 -- val = "restore" restore the settings before the experiment run
 param val:string
 var ani_MU, ani_Icon : boolean
 switch strToLower(val)
 case "read" 
 	self.setting_resetInitBox := resetInitBox(false)
 	self.setting_animMU := animation(false)
 	
 	if NOT ~.simulateWithAnimation
 		animation(false)
 	end
 	
 	if existsObject("EventController") 
 		self.setting_Realtime := EventController.Realtime
 		self.setting_RandomNumbersVariant := EventController.RandomNumbersVariant
 		self.setting_simSpeed := EventController.speed
 		self.setting_IncrRNVariant := EventController.IncrementRandomNumbersVariantOnReset
 		self.setting_SummaryReport := EventController.SummaryReport
 	else
 		return
 	end
 	EventController.speed := 100
 	EventController.Realtime := false
 	EventController.IncrementRandomNumbersVariantOnReset := false
 	EventController.SummaryReport := false
 	
 case "restore"  -- method "Start"
 	resetInitBox(self.setting_resetInitBox)
 	animation(self.setting_animMU)
 	
 	if EventController /=void  
 		EventController.SummaryReport := self.setting_SummaryReport
 		EventController.Realtime := self.setting_Realtime
 		EventController.RandomNumbersVariant := self.setting_RandomNumbersVariant
 		EventController.speed := self.setting_simSpeed
 		EventController.IncrementRandomNumbersVariantOnReset := self.setting_IncrRNVariant
 	end
 
 end
RandomSeed: 441
UUID: 5a728c24-a73f-4615-a3f7-baf04fa8e5e1
$SequenceNumber: 14
$CustomAttributes:
-
 Name: setting_resetInitBox
 ID: 1
 DataType: boolean
 Value: false
-
 Name: setting_Realtime
 ID: 2
 DataType: boolean
 Value: false
-
 Name: setting_RandomNumbersVariant
 ID: 3
 DataType: integer
 Value: 0
-
 Name: setting_simSpeed
 ID: 4
 DataType: integer
 Value: 100
-
 Name: setting_IncrRNVariant
 ID: 5
 DataType: boolean
 Value: false
-
 Name: setting_SummaryReport
 ID: 6
 DataType: boolean
 Value: true
-
 Name: setting_animMU
 ID: 7
 DataType: boolean
 Value: false
-
 Name: setting_animIcon
 ID: 8
 DataType: boolean
 Value: false
